#! /usr/bin/env bash

# libbash 12.1.1 - a collection of useful functions for your Bash scripts
#
# Copyright (C) Georg Lauterbach
# GitHub: https://github.com/georglauterbach/libbash
#
# ---
#
# `libbash` loads functions from modules with the following naming convention:
# A function from the `utils` modules called `exit_checked` is loaded as
# `libbash::utils::exit_checked`. Certain modules (especially `errors`) export
# functions like `libbash::errors::__apply_shell_expansion__`. Functions whose
# names begin and end with `__` are not supposed to be used nor altered by you.
# They are used internally by `libbash`. You can get a list of all functions
# loaded by `libbash` by running `declare -F | grep libbash`.
#
# `libbash` also loads environment variables. You can get a list of all
# environment variables loaded by `libbash` by running `env | grep -i ^LIBBASH__`.

# cSpell: ignore Georg Lauterbach

# shellcheck disable=SC2329

# Ensure this script is available as a whole (e.g., when downloaded)
# and do not execute it otherwise.
{

# ### Initialization
#
# This function calls the initialization routines for `libbash`
# in proper order.
function libbash::__main__() {
  if [[ ${BASH_VERSINFO[0]} -lt 5 ]]; then
    libbash::debug::show_error "libbash only supports Bash version >= 5.0.0"
    libbash::__finish_loading__ --clean
    return 1
  fi

  # if SCRIPT is already set, save it so we can restore it later
  [[ -v SCRIPT ]] && __LIBBASH_SCRIPT_TMP=${SCRIPT}
  SCRIPT='libbash init'
  LOG_LEVEL=${LOG_LEVEL:-info}

  LIBBASH__DIRECTORY=$(realpath -eL "$(dirname "${BASH_SOURCE[0]}")")
  LIBBASH__EXIT_IN_INTERACTIVE_MODE=${LIBBASH__EXIT_IN_INTERACTIVE_MODE:-false}
  LIBBASH__LOADED_MODULES=()
  LIBBASH__VERSION=12.1.1
  LIBBASH__LOG__DATE_FORMAT_SPECIFIER=%Y-%m-%dT%H:%M:%S%:z

  # ! export all variables here first, even if not
  # ! all modules are sourced to satisfy shellcheck
  # ! in applications that use `libbash`
  export LIBBASH__DIRECTORY
  export LIBBASH__EXIT_IN_INTERACTIVE_MODE
  export LIBBASH__LOADED_MODULES
  export LIBBASH__VERSION
  export LIBBASH__IS_LOADED=false

  if [[ ${1:-} =~ ^(--)?version$ ]]; then
    echo "libbash ${LIBBASH__VERSION}"
    libbash::__finish_loading__ --clean
    return 0
  fi

  local MODULE MODULE_LOAD_FUNCTION
  for MODULE in "${@}"; do
    MODULE_LOAD_FUNCTION=libbash::__load_module__::${MODULE}

    if [[ ${LIBBASH__LOADED_MODULES[*]} =~ ${MODULE} ]]; then
      libbash::debug::show_error "module '${MODULE}' loaded more than once"
      libbash::__finish_loading__ --clean
      return 2
    fi

    if [[ $(type -t "${MODULE_LOAD_FUNCTION}") != 'function' ]]; then
      libbash::debug::show_error "module '${MODULE}' does not exist"
      libbash::__finish_loading__ --clean
      return 3
    fi

    if ! "${MODULE_LOAD_FUNCTION}"; then
      libbash::debug::show_error "module '${MODULE}' failed to load"
      libbash::__finish_loading__ --clean
      return 4
    fi

    unset "${MODULE_LOAD_FUNCTION}"
    LIBBASH__LOADED_MODULES+=("${MODULE}")
  done

  [[ ${LIBBASH__LOADED_MODULES[*]} == *log* ]] || function libbash::log::log() { : ; }
  export -f libbash::log::log

  LIBBASH__IS_LOADED=true
  libbash::__finish_loading__ 0
  libbash::log::log 'trace' "Finished 'libbash ${LIBBASH__VERSION}' initialization"
}

# ### Cleanup
#
# When `libbash::__main__` has finished (successfully or unsuccessfully),
# we need to clean up left-over environment variables and functions.
#
# #### Arguments
#
# $1 :: Either '--clean' or the exit code (optional, default=1)
# $2 :: If '--clean' is in $1, the exit code (optional)
function libbash::__finish_loading__() {
  if [[ -v __LIBBASH_SCRIPT_TMP ]]; then
    SCRIPT=${__LIBBASH_SCRIPT_TMP}
    unset __LIBBASH_SCRIPT_TMP
  else
    SCRIPT='prompt or outside of function'
  fi

  if [[ ${1:-} == '--clean' ]]; then
    shift 1

    unset LIBBASH__DIRECTORY
    unset LIBBASH__EXIT_IN_INTERACTIVE_MODE
    unset LIBBASH__LOADED_MODULES
    unset LIBBASH__LOG__IS_LOADED
    unset LIBBASH__VERSION

    unset -f libbash::debug
    unset -f libbash::debug::show_call_stack

    unset -f libbash::debug::show_error
    unset -f libbash::utils::exit_checked
  fi

  unset -f libbash::__main__
  unset -f libbash::__finish_loading__

  if [[ ${1:-1} -gt 0 ]]; then
    LIBBASH__IS_LOADED=false
  fi

  return 0
}

# ### Provide Debug Information
#
# Shows some debug information that `libbash` has collected.
function libbash::debug::print_libbash_debug_information() {
  if ! ${LIBBASH__LOG__IS_LOADED:-false}; then
    libbash::debug::show_error "Debug functionality requires the log module to be loaded and 'LOG_LEVEL' set to 'debug' or 'trace'"
    return 1
  fi

  libbash::log::log 'debug' "Showing 'libbash' debug information"
  libbash::log::log 'debug' "  -> version: ${LIBBASH__VERSION}"
  libbash::log::log 'debug' "  -> loaded modules: ${LIBBASH__LOADED_MODULES[*]}"
  libbash::log::log 'debug' "  -> exit in interactive mode: ${LIBBASH__EXIT_IN_INTERACTIVE_MODE}"
}
export -f libbash::debug::print_libbash_debug_information

# ### Provides Call Stack Information
#
# This function prints the call stack to identify where an error
# originated.
#
# This function will only print a call stack if the stack is
# deeper than 2, because otherwise the error did not originate
# in a function but at global scope.
function libbash::debug::show_call_stack() {
  local STACK_DEPTH CUTOFF=${1:-1}
  [[ ${#FUNCNAME[@]} -gt ${CUTOFF} ]] || return 0

  STACK_DEPTH=$(( ${#FUNCNAME[@]} - CUTOFF ))

  printf '\ncall stack (most recent call first):\n' >&2
  for FUNCTION in "${FUNCNAME[@]:${CUTOFF}:${STACK_DEPTH}}"; do
    printf "  %s\n" "${FUNCTION}" >&2
  done

  printf '\n' >&2
}
export -f libbash::debug::show_call_stack

# ### Show an Error
#
# Indicates an error has happened in `libbash`. Used to display
# errors even when the log module is not (or has not yet been)
# loaded.
function libbash::debug::show_error() {
  printf "%s \e[91mERROR\e[0m %s: %s\n"                      \
    "$(date +"${LIBBASH__LOG__DATE_FORMAT_SPECIFIER}" || :)" \
    "${SCRIPT:-$(basename "${0}")}"                          \
    "${*}" >&2
}
export -f libbash::debug::show_error

# Load the 'log' module
function libbash::__load_module__::log() {
  export LIBBASH__LOG__COLOR_RESET='\e[0m'
  export LIBBASH__LOG__COLOR_TRACE='\e[92m'
  export LIBBASH__LOG__COLOR_DEBUG='\e[36m'
  export LIBBASH__LOG__COLOR_INFO='\e[34m'
  export LIBBASH__LOG__COLOR_WARN='\e[93m'
  export LIBBASH__LOG__COLOR_ERROR='\e[91m'

  export LIBBASH__LOG__IS_LOADED=true

  # ### The Actual Logger
  #
  # This function is used by `log` to print the messages.
  function libbash::log::__log_generic__() {
    local LEVEL=${1:?libbash bug: log level message format must be provided to libbash::log::__log_generic__}
    local COLOR="LIBBASH__LOG__COLOR_${LEVEL^^}"
    shift 1

    # shellcheck disable=SC2059
    printf "%s ${!COLOR}%-5s${LIBBASH__LOG__COLOR_RESET} %s: %s\n" \
      "$(date +"${LIBBASH__LOG__DATE_FORMAT_SPECIFIER}" || :)"     \
      "${LEVEL^^}"                                                 \
      "${SCRIPT:-$(basename "${0}")}"                              \
      "${*}"
  }
  export -f libbash::log::__log_generic__

  # ### The Logging Functions
  #
  # `log` uses five different log levels and behaves as you would
  # expect from a log function: you provide the log level as the
  # first argument and the message in the consecutive ones. The
  # default log level is 'info'. The global log level is defined
  # in the `LOG_LEVEL` variables. The global variable `SCRIPT`
  # defines a prefix of the message that is being logged.
  #
  # #### Log Level
  #
  # The provided log level, as well as the environment variable
  # `LOG_LEVEL`, can be one of
  #
  # - trace (log all messages)
  # - debug
  # - info
  # - warn
  # - error
  # - off (log no messages)
  #
  # The default log level is 'info'.
  #
  # #### Return Codes
  #
  # This function is infallible.
  #
  # #### Arguments
  #
  # $1     :: log level
  # ${@:1} :: message
  function libbash::log::log() {
    [[ ${LOG_LEVEL:-} == off ]] && return 0

    if [[ -z ${1+set} ]]; then
      libbash::log::log 'warn' "'log' called without log level"
      return 0
    elif [[ ! ${1} =~ ^(error|warn|info|debug|trace)$ ]]; then
      libbash::log::log 'warn' "'log' called with unknown log level (use 'error', 'warn', 'info', 'debug', or 'trace')"
      return 0
    elif [[ -z ${2+set} ]]; then
      libbash::log::log 'warn' "'log' called without message"
      return 0
    fi

    local MESSAGE_LOG_LEVEL=${1}
    shift 1

    # Scoping of dictionaries beyond `source` / in the global namespace is
    # even more horrendous that normal scoping in Bash - hence, we avoid it
    # and put the dictionary here.
    declare -A LOG_LEVEL_MAPPING=([off]=0 [error]=1 [warn]=2 [info]=3 [debug]=4 [trace]=5 )
    if [[ -z ${LOG_LEVEL_MAPPING[${LOG_LEVEL:=info}]:-} ]]; then
      local OLD_LOG_LEVEL=${LOG_LEVEL}
      export LOG_LEVEL='debug'
      libbash::log::log 'warn' "Log level '${OLD_LOG_LEVEL}' unknown - resetting to log level '${LOG_LEVEL}'"
    fi

    [[ ${LOG_LEVEL_MAPPING[${LOG_LEVEL}]} -lt ${LOG_LEVEL_MAPPING[${MESSAGE_LOG_LEVEL}]} ]] && return 0

    if [[ ${LOG_LEVEL_MAPPING[${MESSAGE_LOG_LEVEL}]} -lt 2 ]]; then
      libbash::log::__log_generic__ "${MESSAGE_LOG_LEVEL}" "${*}" >&2
    else
      libbash::log::__log_generic__ "${MESSAGE_LOG_LEVEL}" "${*}"
    fi
  }
}

# Load the 'errors' module
function libbash::__load_module__::errors() {
  # cSpell: ignore gsub

  # Call `libbash::errors::__log_unexpected_error__` with additional information
  # when the ERR trap is triggered.
  set -E -o pipefail
  shopt -s inherit_errexit
  trap 'libbash::errors::__log_unexpected_error__ "${FUNCNAME[0]:-}" "${BASH_COMMAND:-}" "${LINENO:-}" "${?:-}"' ERR

  # ### Remove Newlines from a String
  #
  # This function removes newlines from a given string,
  # replacing them with " ".
  #
  # #### Arguments
  #
  # $1 :: The string to libbash::utils::escape (optional, default=unknown)
  #
  # #### Return Codes
  #
  # This function is infallible. Hence, it always returns with
  # return code 0.
  function libbash::errors::__remove_newlines__() {
    local STRING=${1:-unknown}
    echo "${STRING//$'\n'/ }"
  }
  export -f libbash::errors::__remove_newlines__

  # ### Expand a String
  #
  # This function expands a given string
  #
  # #### Arguments
  #
  # $1 :: The string to expand (optional, default=unknown)
  #
  # #### Attention
  #
  # This function uses `eval` to libbash::utils::escape the string in the end.
  # While considerable effort has been put into proper escaping,
  # no one can guarantee that all pitfalls and libbash::utils::escape hatches
  # have been eliminated that could lead to arbitrary code execution
  # with the `eval` at the end.
  #
  # Of special importance is the replacement '//\$\(/\\$\(', which
  # replaces all '$(' with '\$('.
  #
  # #### References
  #
  # StackOverflow
  #   - https://stackoverflow.com/a/20316582
  function libbash::errors::__apply_shell_expansion__() {
    local DELIMITER="__libbash::errors::__apply_shell_expansion___delimiter__"
    local STRING_TO_ESCAPE=${1:-unknown}
    STRING_TO_ESCAPE=$(libbash::errors::__remove_newlines__ "${STRING_TO_ESCAPE}")
    STRING_TO_ESCAPE=${STRING_TO_ESCAPE//\$\(/\\$\(}

    eval "cat <<${DELIMITER}"$'\n'"${STRING_TO_ESCAPE}"$'\n'"${DELIMITER}"
  }
  export -f libbash::errors::__apply_shell_expansion__

  # ### Log the Error Event
  #
  # This function is called when an unhandled error signal is thrown.
  # It prints information about the error (where it originated, etc.)
  # and also calls `libbash::debug::show_call_stack` to possibly print a
  # call stack if `libbash::debug::show_call_stack` deems it useful.
  #
  # #### Explanations
  #
  # The code below has to be used in conjunction with the `ERR` trap
  # above. The trap uses special variable that Bash sets to show the
  # user what happened.
  #
  # Furthermore, the `eval echo "${2:-unknown}"` expands all variables
  # in `${2}` (which contains the value of `${BASH_COMMAND}`, i.e. the command
  # that was executed). This is neat because the user can see the expanded
  # version of the command too.
  #
  # #### Attention
  #
  # Underscored functions are not unset at the end of the sourcing
  # process, but they should only be used by `libbash` modules, not
  # by applications / other libraries using `libbash`.
  #
  # Please also not the "Attention" section of `libbash::errors::__apply_shell_expansion__`.
  #
  # #### Arguments
  #
  # $1 :: Name of the function the error happened in
  # $2 :: The command that caused the error
  # $3 :: The line number in which $2 was executed
  # $4 :: The return code of $2
  function libbash::errors::__log_unexpected_error__() {
    # shellcheck disable=SC2155
    local MESSAGE="unexpected error occurred:
    script:     ${SCRIPT:-"${0}"}
    function:   ${1:-prompt or outside of function}
    command:
      plain:    $(libbash::errors::__remove_newlines__ "${2:-unknown}")
      expanded: $(libbash::errors::__apply_shell_expansion__ "${2:-unknown}")
    line:       ${3:-unknown}
    exit code:  ${4:-unknown}"

    libbash::debug::show_error "${MESSAGE}"
    libbash::debug::show_call_stack 2
    return 0
  }
  export -f libbash::errors::__log_unexpected_error__
}

# Load the 'utils' module
function libbash::__load_module__::utils() {
  # cSpell: ignore mawk

  # ### Exit With Conditions
  #
  # This function will call `exit` when not running interactively
  # or when 'LIBBASH__EXIT_IN_INTERACTIVE_MODE' is set to 'true'.
  # Otherwise, it calls `return`.
  #
  # #### Arguments
  #
  # $1 :: the return code (optional, default=1)
  function libbash::utils::exit_checked() {
    local CODE=${1:-1}
    local METHOD='return'

    if [[ ${-} != *i* ]] || ${LIBBASH__EXIT_IN_INTERACTIVE_MODE:-false}; then
      METHOD='exit'
    fi

    if [[ ${CODE} =~ ^[0-9]$ ]]; then
      "${METHOD}" "${CODE}"
    else
      libbash::debug::show_error "Supplied non-number code ('${CODE}') to libbash::utils::exit_checked"
      "${METHOD}" 1
    fi
  }
  export -f libbash::utils::exit_checked

  # ### Split a String with a Delimiter Into an Array
  #
  # Splitting a string into an array can be done in various ways.
  # The approach taken below is based on [1] but avoids 'awk'
  # because 'awk' is assumed to be 'gawk'. Sometimes, 'awk' is
  # something else ('mawk'), though, and this is not immediately
  # apparent and hence, error-prone.
  #
  # [1]: StackOverflow, https://stackoverflow.com/a/45201229
  #
  # #### Arguments
  #
  # $1 :: array name (this array is created)
  # $2 :: string to split
  # $3 :: delimiter (optional, default=:)
  #
  # #### Attention
  #
  # Backslash (`\`) does not work as a delimiter because the escaping logic
  # is simple and just removes backslashes.
  function libbash::utils::split_into_array() {
    local ARRAY_NAME=${1:?array name is required}
    local STRING_TO_SPLIT=${2:?string to split is required}
    local DELIMITER=${3:-':'}
    local UNESCAPED_DELIMITER=${DELIMITER//\\/}

    STRING_TO_SPLIT=${STRING_TO_SPLIT#"${UNESCAPED_DELIMITER}"} # remove prefix
    STRING_TO_SPLIT=${STRING_TO_SPLIT%"${UNESCAPED_DELIMITER}"} # remove suffix

    readarray -t -d '' "${ARRAY_NAME}" \
      < <(printf '%s' "${STRING_TO_SPLIT}" | sed "s|${DELIMITER}|\x0|g")
  }
  export -f libbash::utils::split_into_array

  # ### Check If a Line Is a Comment or Blank
  #
  # Checks if the provided first argument starts with
  # a comment or whether the line is blank.
  #
  # #### Arguments
  #
  # $1 :: line to be checked
  # $2 :: comment symbol (optional, default=#)
  function libbash::utils::line_is_comment_or_blank() {
    local COMMENT_SYMBOL
    COMMENT_SYMBOL=${2:-#}
    grep -qE "^\s*$|^\s*${COMMENT_SYMBOL}" <<< "${1:-}"
  }
  export -f libbash::utils::line_is_comment_or_blank

  # ### Escape All But Backslashes
  #
  # Takes a string and an libbash::utils::escape character and
  # puts backslashes in front. Does not accept
  # backslashes as libbash::utils::escape character. The libbash::utils::escape
  # character must be a single character.
  #
  # #### Arguments
  #
  # $1 :: string to be libbash::utils::escaped
  # $2 :: character that must be libbash::utils::escaped
  function libbash::utils::escape() {
    [[ ${2} =~ .*\\.* ]] && {
      libbash::debug::show_error \
        "Escape character is not allowed to be or contain a backslash"\
        "(use 'libbash::utils::escape_backslash')"
      return 1
    }

    libbash::utils::parameter_is_not_empty "${1}" || {
      libbash::debug::show_error 'No string to be libbash::utils::escaped provided'
      return 1
    }

    libbash::utils::parameter_is_not_empty "${2}" || {
      libbash::debug::show_error 'No libbash::utils::escape character(s) provided'
      return 1
    }

    [[ ${#2} -ge 2 ]] && {
      libbash::debug::show_error 'More than two parameters provided'
      return 1
    }

    printf '%s' "${1//${2}/\\${2}}"
  }
  export -f libbash::utils::escape

  # ### Escape Backslashes Only
  #
  # Takes a string and puts s backslash more
  # in front of an already present backslash.
  #
  # #### Arguments
  #
  # $1 :: string to be libbash::utils::escaped
  function libbash::utils::escape_backslash() {
    # shellcheck disable=SC1003
    printf '%s' "${1//'\'/'\\'}"
  }
  export -f libbash::utils::escape_backslash

  # ### Exit Without Error
  #
  # Just a wrapper around `exit 0`.
  function libbash::utils::exit_success() { exit 0 ; }
  export -f libbash::utils::exit_success

  # ### Exit With Error
  #
  # Just a wrapper around `exit 1`. Another exit
  # code can be supplied as well.
  #
  # #### Arguments
  #
  # $1 :: exit code (optional, default=1)
  # $2 :: message (optional, default='' (no output is printed))
  function libbash::utils::exit_failure() {
    local CODE=${1:-1}
    shift 1

    if [[ ! ${CODE} =~ ^[0-9]+$ ]]; then
      libbash::debug::show_error "'libbash::utils::exit_failure' was called with non-number exit code"
      libbash::debug::show_call_stack
      exit 1
    fi

    if [[ ${CODE} -eq 0 ]] || [[ ${CODE} -ge 127 ]]; then
      libbash::debug::show_error "'libbash::utils::exit_failure' was called with exit code 0 or >127"
      libbash::debug::show_call_stack
      exit 1
    fi

    libbash::utils::parameter_is_not_empty "${1:-}" && libbash::debug::show_error "${1}"
    exit "${CODE}"
  }
  export -f libbash::utils::exit_failure

  # ### Exit Without Error
  #
  # Just a wrapper around `return 0`. This should only be
  # used at the very end of a function is it relies on Bash
  # settings the return code of the last command as the exit
  # code of the function.
  function libbash::utils::return_success() { return 0 ; }
  export -f libbash::utils::return_success

  # ### Exit With Error
  #
  # Just a wrapper around `return 1`. This should only be
  # used at the very end of a function is it relies on Bash
  # setting the return code of the last command as the exit
  # code of the function.
  #
  # #### Arguments
  #
  # $1 :: message (optional, default='')
  function libbash::utils::return_failure() {
    if [[ ! ${1:-1} =~ ^[0-9]+$ ]]; then
      libbash::debug::show_error "'libbash::utils::return_failure' was called with non-number exit code"
      libbash::debug::show_call_stack
      exit 1
    fi

    if [[ ${1:-1} -eq 0 ]] || [[ ${1:-1} -ge 128 ]]; then
      libbash::debug::show_error "'libbash::utils::return_failure' was called with exit code 0 or >127"
      libbash::debug::show_call_stack
      exit 1
    fi

    libbash::utils::parameter_is_not_empty "${*}" && libbash::debug::show_error "${*}"
    return "${1:-1}"
  }
  export -f  libbash::utils::return_failure

  # ### Exit with Error and Show the Callstack
  #
  # This function exits with exit code 1 but also
  # prints information about the call stack. Another
  # exit code can be supplied as well.
  #
  # #### Arguments
  #
  # Same as `libbash::utils::exit_failure`.
  function libbash::utils::exit_failure_show_callstack() {
    libbash::utils::parameter_is_not_empty "${2:-}" && libbash::debug::show_error "${2}"
    libbash::debug::show_call_stack
    libbash::utils::exit_failure "${1:-}"
  }
  export -f libbash::utils::exit_failure_show_callstack

  # ### Check if Variable is Set
  #
  # This function checks if an environment variable is set.
  #
  # #### Arguments
  #
  # $1 :: the variable's name
  function libbash::utils::var_is_set() {
    [[ -v ${1:-__UNSET__} ]]
  }
  export -f libbash::utils::var_is_set

  # ### Check if Variable is Set and Not Empty
  #
  # This function checks if an environment variable is set
  # and not empty.
  #
  # #### Arguments
  #
  # $1 :: the variable's name
  function libbash::utils::var_is_set_and_not_empty() {
    libbash::utils::var_is_set "${1}" && [[ -n ${!1:-} ]]
  }
  export -f libbash::utils::var_is_set_and_not_empty

  # ### Tell Whether a Parameter to a Function is Set and Not Empty
  #
  # This function returns true if the variable given in $1
  # is not null and not empty.
  #
  # #### Arguments
  #
  # $1 :: the parameter you want to check
  #
  # #### Example
  #
  # ```bash
  # function my_echo() {
  #   libbash::utils::parameter_is_not_empty "${1}"
  #   echo "${1}"
  # }
  # ```
  function libbash::utils::parameter_is_not_empty() {
    [[ -n ${1:-} ]]
  }
  export -f libbash::utils::parameter_is_not_empty

  # ### Ask a Question
  #
  # This function states a question and returns the result
  # in a variable name given to this function.
  #
  # #### Arguments
  #
  # $1 :: question
  # $2 :: variable name to store the result in
  function libbash::utils::ask_question() {
    libbash::utils::parameter_is_not_empty "${1}" || {
      libbash::debug::show_error 'No question provided'
      return 1
    }

    libbash::utils::parameter_is_not_empty "${2}" || {
      libbash::debug::show_error 'No variable to store result in provided'
      return 1
    }

    local QUESTION=${1}
    local -n VARIABLE_TO_STORE_ANSWER_IN=${2}

    # shellcheck disable=SC2034
    read -r -p "${QUESTION} " VARIABLE_TO_STORE_ANSWER_IN
  }
  export -f libbash::utils::ask_question

  # ### Ask a Question - Special Case
  #
  # This function is for the special case where the question
  # is a yes-or-no question (binary). It will state the question
  # and it can be given a default answer. It will return true or
  # false depending on the default and the user input.
  #
  # #### Arguments
  #
  # $1 :: question
  # $2 :: default (optional, default=no)
  function libbash::utils::ask_yes_no_question() {
    libbash::utils::parameter_is_not_empty "${1}" || {
      libbash::debug::show_error 'No question provided'
      return 1
    }

    local ANSWER DEFAULT_STRING
    local DEFAULT=${2:-no} YES_REGEXP='^(y|yes)$'
    DEFAULT=${DEFAULT,,}

    if [[ ${DEFAULT} =~ ${YES_REGEXP} ]]; then
      DEFAULT_STRING=' [Y/n]'
    else
      DEFAULT_STRING=' [y/N]'
    fi

    libbash::utils::ask_question "${1}${DEFAULT_STRING}" ANSWER

    if [[ ${DEFAULT} =~ ${YES_REGEXP} ]] && [[ -z ${ANSWER} ]]; then
      return 0
    elif [[ ${DEFAULT} =~ ^(n|N|no|No)$ ]] && [[ -z ${ANSWER} ]]; then
      return 1
    fi

    [[ ${ANSWER,,} =~ ${YES_REGEXP} ]]
  }
  export -f libbash::utils::ask_yes_no_question

  # ### Is a Program in ${PATH}?
  #
  # This function returns with exit code 0 (success) if
  # the argument given is in ${PATH}, otherwise exit code
  # 1 (failure) is returned.
  #
  # #### Arguments
  #
  # $1 :: executable to check
  function libbash::utils::is_in_path() {
    libbash::utils::parameter_is_not_empty "${1}" || {
      libbash::debug::show_error 'No name for an executable provided'
      return 1
    }

    command -v "${1}" &>/dev/null
  }
  export -f libbash::utils::is_in_path

  # ### Is a Program Not in ${PATH}?
  #
  # This function returns with exit code 1 (failure) if
  # the argument given is not in ${PATH}, otherwise exit
  # code 0 (success) is returned.
  #
  # #### Arguments
  #
  # $1 :: executable to check
  function libbash::utils::is_not_in_path() {
    ! libbash::utils::is_in_path "${1}"
  }
  export -f libbash::utils::is_not_in_path

  # ### Check Whether a Directory is Empty
  #
  # This function checks whether a directory
  # contains files or other directories, and
  # returns false if so.
  #
  # #### Arguments
  #
  # $1 :: directory to check
  function libbash::utils::dir_is_empty() {
    libbash::utils::parameter_is_not_empty "${1}" || {
      libbash::debug::show_error 'No name for an executable provided'
      return 1
    }

    [[ -n $(find "${1}" -maxdepth 0 -empty) ]]
  }
  export -f libbash::utils::dir_is_empty

  # ### Check Whether a Directory is Not Empty
  #
  # This function checks whether a directory
  # contains files or other directories, and
  # returns true if so.
  #
  # #### Arguments
  #
  # $1 :: directory to check
  function libbash::utils::dir_is_not_empty() {
    ! libbash::utils::dir_is_empty "${1}"
  }
  export -f libbash::utils::dir_is_not_empty

  # ### Checks Whether a Variable Evaluates to True
  #
  # This function checks, when expanding the string
  # and making it lowercase, whether this string
  # is "true", "yes" or "y".
  #
  # #### Arguments
  #
  # $1 :: name of environment variable to check
  function libbash::utils::value_is_true() {
    declare -n __VAR=${1}
    [[ ${__VAR,,} =~ ^(true|y(es)?)$ ]]
  }
  export -f libbash::utils::value_is_true
}

libbash::__main__ "${@}"

}
